### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by TabiasP** [rocket-pool/beacon-chain-simulator#1]
When attempting to migrate the casper contract, I am presented with the following error:
"Compilation failed. See above" and it points to a section in the Withdraw.sol contract :

`.\beacon-chain-simulator\contracts\casper>truffle migrate`

`Error parsing C:\Users\thede\Desktop\beacon-chain-simulator\contracts\Withdraw.sol: `

`ParsedContract.sol:40:31: ParserError: Expected ',' but got 'payable'
    function withdraw(address payable _to, uint256 _amount) external onlyOwner {`

**Comment by moles1** [comment]
This is likely due to an outdated version of truffle and solc - please upgrade to truffle 5.0.3 and solc ^0.5.0 :)
