### ISSUE TITLE
Unable to get validator status

### ISSUE THREAD

**Issue by TabiasP** [rocket-pool/beacon-chain-simulator#2]
I've started my POW chain, Beacon chain is up and running. I've made a successful validator deposit, but when I go to run the validator-activity script, I get the error `A server error occurred: Unable to get validator status`.

**Comment by moles1** [comment]
Hi @TabiasP, that sounds like you're running the activity script with a pubkey for a validator which hasn't been added yet.

Make sure to make a deposit to the Casper Deposit contract first using the validator-deposit script, e.g.:

```
node scripts/validator-deposit.js \
    --depositContract 0x509f8ca318F3EACabeC9589dc7cc18b393129C9A \
    --from 0xc46c4661dd9bd08627a38b5fcba15776ae667978 \
    --amount 32 \
    --pubkey 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcd01 \
    --withdrawalPubkey 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
```

Be sure that:
- The `depositContract` parameter matches the address of the deposit contract deployed when you ran `truffle migrate`
- The `amount` is at least 32 (the minimum ether requirement for a validator to be added)
- The `pubkey` you use when running the validator-activity script matches the one you use here

FYI the full steps are on the readme here: https://github.com/rocket-pool/beacon-chain-simulator

Hope this helps!

**Comment by moles1** [comment]
Apologies, there appear to be breaking changes to the chainsafesystems/ssz dependency which would explain the issues you're experiencing - resolving now

**Comment by moles1** [comment]
OK the issues are resolved, please:
- pull latest changes from this repo
- update your node modules

Note that if your deposit via the validator-deposit script is successfully registered, you should see output similar to the following in the beacon process:

`Added validator 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcd01 with balance 32000000000 at index 0`
